#FROM arm32v7/python:3.6-stretch
FROM resin/raspberrypi3-python:3.6

WORKDIR /root/

COPY blockchain.py .
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "./blockchain.py"]