apiVersion: v1
kind: Service
metadata:
  name: hackernoonbc-svc
  labels:
    app: hackernoonbc
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30865
    protocol: TCP
  selector:
    app: hackernoonbc